#This program says hello, asks for name, and gives the length. (written in vim)

print('Boozhoo creation!')
print('What is your name?')
usersName = input()
print('Nice to meet you, ' + usersName + '!')
print('The length of  your name is: ' + str(len(usersName)))
print('How old are you?')
usersAge = input()
print('You will be ' + str(int(usersAge) + 1) + ' in one year!')
